name: Deploy to Google Apps Script

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Clasp
        run: npm install -g @google/clasp

      - name: Create creds.json file
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: echo "$GCP_CREDENTIALS" > $HOME/.clasprc.json

      - name: Clone Google Apps Script project
        run: clasp clone ${{ secrets.APPS_SCRIPT_ID }} --rootDir "${{ runner.temp }}/appscript_project"

      - name: Setup .claspignore
        run: |
          echo "*" > .claspignore
          echo "!src/apps_script/" >> .claspignore
          echo "src/apps_script/*" >> .claspignore
          echo "!src/apps_script/schedule.js" >> .claspignore

      - name: Stream schedule.js to Apps Script
        working-directory: "${{ runner.temp }}/appscript_project"
        run: clasp push --force
